# See https://github.com/dawaltconley/cfn-static-website

AWSTemplateFormatVersion: 2010-09-09
Description: Resources for a static website

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W3002 # ignore warnings about dependency on the `package` command

Parameters:
  # SiteDomain:
  #   Type: String
  ContactEmail:
    Type: String

Resources:
  ContactFormApi: # see https://github.com/dawaltconley/contact-api/blob/main/docs/template.md
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./node_modules/@dawaltconley/contact-api/dist/build/template.yaml
      Parameters:
        Email: !Ref ContactEmail
        Required: 'name,email,subject,message'
        Honeypot: 'fax_number'
        AllowOrigin: '*'
        # AllowOrigin: !Sub 'https://${SiteDomain}'
